### ISSUE TITLE
mongo-dump-stream

### ISSUE THREAD

**Issue by marcolino** [punkave/mongo-dump-stream#10]
On a Centos 6.6 box:

```
$ mongo-dump-stream mongodb://localhost/mydb
js-bson: Failed to load c++ bson extension, using pure JS version
module.js:338
    throw err;
    ^

Error: Cannot find module './build/Debug/buffertools.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/mongo-dump-stream/node_modules/buffertools/buffertools.js:26:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Any clue?

**Comment by boutell** [comment]
I suspect you upgraded to a newer version of node and a dependency problem
was created. Try "npm install -g mongo-dump-stream" again.

On Mon, Oct 12, 2015 at 4:50 AM, marcolino notifications@github.com wrote:

> On a Centos 6.6 box:
> 
> $ mongo-dump-stream mongodb://localhost/mydb > dump
> js-bson: Failed to load c++ bson extension, using pure JS version
> module.js:338
>     throw err;
>     ^
> 
> Error: Cannot find module './build/Debug/buffertools.node'
>     at Function.Module._resolveFilename (module.js:336:15)
>     at Function.Module._load (module.js:286:25)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.<anonymous> (/usr/lib/node_modules/mongo-dump-stream/node_modules/buffertools/buffertools.js:26:20)
>     at Module._compile (module.js:434:26)
>     at Object.Module._extensions..js (module.js:452:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
> 
> Any clue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/punkave/mongo-dump-stream/issues/10.

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by StephenWilson** [comment]
I have just experienced the same problem, your suggestion to reinstall mongo-dump-stream didn't change anything.

To add a little, I noticed that the Debug folder in buffertools/build did not exist, it did however have a Release folder.
