### ISSUE TITLE
Mongo-Load-Stream

### ISSUE THREAD

**Issue by NewMongo** [punkave/mongo-dump-stream#13]
Hi, Iam extremely new to Mongo. and the first task that I was assigned was to restore a back up of a mongobd. This in itself wouldn't be a problem, but the back-up was taken by a guy using Mongo-dump-Stream, which meant that when I used MongoRestore command, it didn't work. This is when I realised that the other option was to use Mongo-Load-Stream. This is where the problem started. I cannot use it, the function throws an error. I tried running it on the dev server (using Linux) but it didnrt work either. Installed Node.js for windows but with the same issue. Can someone please please help me resolve this, I really am a novice at this and the guy who took the back-up is on vacation! Help needed urgently!

**Comment by boutell** [comment]
Hi,

I would be willing to peek at this file for you if you are able to share it
with me and it's not too ridiculously huge?

You can contact me directly at tom@punkave.com, don't attach it publicly
here in github.

On Fri, May 20, 2016 at 10:28 AM, NewMongo notifications@github.com wrote:

> Hi, Iam extremely new to Mongo. and the first task that I was assigned was
> to restore a back up of a mongobd. This in itself wouldn't be a problem,
> but the back-up was taken by a guy using Mongo-dump-Stream, which meant
> that when I used MongoRestore command, it didn't work. This is when I
> realised that the other option was to use Mongo-Load-Stream. This is where
> the problem started. I cannot use it, the function throws an error. I tried
> running it on the dev server (using Linux) but it didnrt work either.
> Installed Node.js for windows but with the same issue. Can someone please
> please help me resolve this, I really am a novice at this and the guy who
> took the back-up is on vacation! Help needed urgently!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/punkave/mongo-dump-stream/issues/13

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
