### ISSUE TITLE
Pipe db directly on response (express)

### ISSUE THREAD

**Issue by Oldwo1f** [punkave/mongo-dump-stream#4]
Hi,
I am trying to use your nice module to send databackbackup trought HTTP.
I am base on express wich means that i sould pipe your writeStream directly into res.

```
return mds.dump('mongodb://localhost:27017/madmin', res, function(err) {
       if (!err) { // Everything was sent 
       } 
});
```

When i launch this from a browser, the file start to upload in browser, but it stay at 0%.

Any idea of what happend here?

Other thing: your plugin works great when i write db to file (each time this file weight is 326.3) But when i try to download it from browser with the above code, the weight of the file the browser is attempting to download is different from 326.3.    And i dont change database datas.

Any infos are welcome

**Comment by Oldwo1f** [comment]
is someone here?

**Comment by boutell** [comment]
Hi, I think I don't close the stream. Because you might want to write other
stuff. But in practice you likely wouldn't.

Try closing the stream after the callback.

**Comment by Oldwo1f** [comment]
i tryed that

```
// in callback

res.status(200).end()
```

**Comment by Oldwo1f** [comment]
I am trying at the moment a solution wich consit to first store the file drive then read it and send it to client

``` javascript

var out = fs.createWriteStream('test/tt.db');
        return mds.dump('mongodb://localhost:27017/madmin', out, function(err) {
          console.log(err);
          if (err) { // Everything was sent 
          }else
          {
            var rs = fs.createReadStream('test/tt.db')
            rs.pipe(res)
     }
});
```

The file created size is 329ko and the filed uploaded size is 20.6ko

any idea of whats append here?

**Comment by boutell** [comment]
Same issue. The stream has not been closed so the file has not been flushed to disk. Close it, wait for the event that says it is really closed.

**Comment by Oldwo1f** [comment]
can you explain me how to close it.
It would be super cool

**Comment by Oldwo1f** [comment]
i figured out a crappy solution with a 3sec time out and it works, but i would like to close this stream...

```
out.end();  // <-- i tryed
out.close();  // <-- i tryed

out.on('end', function() {
    console.log('there will be no more data.'); //  But script never come here
});
```

how can i access your stream? in order to close it

**Comment by boutell** [comment]
You want out.end(), and the 'finish' event. Or a callback to end(). See the
docs for end().

On Sun, Apr 26, 2015 at 5:57 PM, Oldwo1f notifications@github.com wrote:

> i figured out a crappy solution with a 3sec time out and it works, but i
> would like to close this stream...
> 
> out.end();  // <-- i tryed
> out.close();  // <-- i tryed
> 
> out.on('end', function() {
>     console.log('there will be no more data.'); //  But script never come here
> });
> 
> how can i access your stream? in order to close it
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/punkave/mongo-dump-stream/issues/4#issuecomment-96439061
> .

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
